import Head from 'next/head'
import Fieldstable from '../components/FieldsTable'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
         <Fieldstable />
      </main>
    </div>
  )
}
