import Head from 'next/head'
import { FC } from 'react';
import Profile from '../components/Profile';

const Home:FC = () => { 
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
         <Profile/>
      </main>
    </div>
  )
};

export default Home;