import Head from 'next/head'
import { useDispatch, useSelector } from 'react-redux';

import Profile from '../components/Profile'
import { getConfigureFileds, selectFields } from '../features/configure/configureSlice';

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
         <Profile/>
      </main>
    </div>
  )
};